---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == "RedHat"

# oddjob requires dbus and needs to restart it
# https://digitalchild.info/oddjobd-fails-start-fixed/

- name: Install dbus package for RedHat
  yum:
    name: dbus
    state: present
  notify:
    - Restart messagebus
  tags:
    - dbus_pkg

- name: Make sure messagebus service is running
  service:
    name: messagebus
    state: started
  register: messagebus_service_started
  tags:
    - dbus_pkg

- name: Make sure messagebus service is enabled
  service:
    name: messagebus
    enabled: yes
  tags:
    - dbus_config

- name: Install oddjob package for RedHat
  yum:
    name: "{{ oddjob_pkg }}"
    state: present
  notify:
    - Restart oddjobd
  tags:
    - oddjob_pkg

- name: Install oddjob helper package for RedHat
  yum:
    name: "{{ item }}"
    state: present
  with_items: oddjob_helper_pkg
  notify:
    - Restart oddjobd
  tags:
    - oddjob_pkg

- name: Configure oddjob service
  template:
    src: oddjobd.conf.j2
    dest: /etc/oddjobd.conf
  notify:
    - Restart oddjobd
  tags:
    - oddjob_config

- name: Make sure oddjobd service is running
  service:
    name: oddjobd
    state: started
  register: oddjob_service_started
  tags:
    - oddjob_pkg
    - oddjob_config

- name: Make sure oddjobd service is enabled
  service:
    name: oddjobd
    enabled: yes
  tags:
    - oddjob_config
